name: buking
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

version: 1.0.14+14

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: 0.27.7
  dio: 5.7.0
  logger: 1.1.0
  get_it: 7.2.0
  flutter_downloader: 1.11.1
  intl: 0.19.0
  top_snackbar_flutter: 3.1.0
  retrofit: 4.4.1
  dots_indicator: 2.1.0
  json_annotation: 4.8.1
  hive_flutter: 1.1.0
  flutter_svg: 2.0.17
  flutter_svg_provider: 1.0.7
  carousel_slider: ^5.0.0
  expandable: 5.0.1
  image_picker: 1.1.2
  file_picker: 10.0.0
  cached_network_image: 3.3.1
  url_launcher: 6.1.6
  firebase_core: 3.10.1
  firebase_messaging: 15.2.1
  flutter_local_notifications: 18.0.1
  package_info_plus: 8.3.0
  crypto: 3.0.2
  flutter_rating_bar: 4.0.1
  device_info_plus: 11.3.0
  simple_gradient_text: 1.2.4
  flutter_slidable: 3.0.0
  collection: 1.19.0
  shared_preferences: 2.5.3
#  html_unescape: 2.0.0
  percent_indicator: 4.2.2
#  youtube_player_flutter: 9.1.1
#  no_screenshot: 0.3.1
#  flutter_widget_from_html: 0.16.0
#  flutter_inappwebview: 6.1.5
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 9.1.5
  hive_generator: 2.0.1
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  flutter_launcher_icons: 0.13.1
  story_view: 0.16.5

dependency_overrides:
  path_provider: 2.1.5

flutter_icons:
  android: true
  ios: true
  image_path: "asset/launcher.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/fi-sr-apps.svg
    - asset/fi-sr-ff.svg
    - asset/fi-sr-heart.svg
    - asset/fi-sr-home.svg
    - asset/fi-sr-user.svg
    - asset/logo.png
    - asset/fi-sr-home.png
    - asset/bag_2.png
    - asset/bag_1.png
    - asset/notif.png
    - asset/groop1.png
    - asset/groop2.png
    - asset/groop3.png
    - asset/welcom.png
    - asset/notif_aa.png
    - asset/home_ban.png
    - asset/tab1.svg
    - asset/tab2.svg
    - asset/tab3.svg
    - asset/tab4.svg
    - asset/tab5.svg
    - asset/mini_logo.png
    - asset/prof_1.png
    - asset/prof_2.png
    - asset/prof_3.png
    - asset/prof_ic_1.png
    - asset/prof_ic_2.png
    - asset/prof_ic_3.png
    - asset/prof_ic_4.png
    - asset/dsr_1.png
    - asset/dsr_2.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
